### ISSUE TITLE
DBCursor should be Closeable

### ISSUE THREAD

**Issue by antigremlin** [mongojack/mongojack#108]
As a `com.mongodb.DBCursor` wrapper, the class `org.mongojack.DBCloseable` should implement `java.io.Closeable`. This will allow to use it in a try-with-resources statement like this:

    try (DBCursor cursor = collection.find()) {
      //
    }

Plain mongo `DBCursor` is `Closeable` by implementing `com.mongodb.Cursor` and thus is `AutoCloseable` as well.

**Comment by linjer** [comment]
Looks like this was addressed in the following PR: https://github.com/mongojack/mongojack/commit/1775c91dd996b1a40aec051a6e5e99831c9fed22

**Comment by antigremlin** [comment]
Yes, looks good.
