### ISSUE TITLE
Suspicious code in ObjectIdDeserializers

### ISSUE THREAD

**Issue by jyemin** [mongojack/mongojack#120]
Looking at:
   
     https://github.com/mongojack/mongojack/blob/mongojack-2.5.0/src/main/java/org/mongojack/internal/ObjectIdDeserializers.java#L45

It serializes an ObjectId to a String using ObjectId#toString.  But the toString method does not have a documented stable format, and in fact has changed in the 3.0 driver.

Rather than ObjectId#toString(), an ObjectId should be serialized to a String using ObjectId#toHexString()

**Comment by benmccann** [comment]
Fixed here - https://github.com/mongojack/mongojack/commit/b455901280a2ca20f70b666f5a3db63960701641

**Comment by benmccann** [comment]
Thanks for tracking it down. I released a new version 2.5.1 that hopefully will work for you. Mind testing it out?
