### ISSUE TITLE
mongojack.org out of date

### ISSUE THREAD

**Issue by lukehutch** [mongojack/mongojack#122]
Hi, mongojack.org says the most recent version is 2.1.0. Maybe that site should just point to this github repo if this is the definitive home for mongojack now?

**Comment by mholding** [comment]
Very good point!  Super sloppy and irresponsible

**Comment by benmccann** [comment]
@bastien03 @roughy I don't have access to mongojack.org. Do you?

**Comment by kdkeck** [comment]
@jroper the mongojack.org domain is registered to you.  Would you mind either updating it or transferring it to someone who will?

**Comment by jroper** [comment]
mongojack.org is hosted by GitHub pages on this repo:

```
$ host mongojack.org
mongojack.org has address 192.30.252.153
mongojack.org has address 192.30.252.154
$ host 192.30.252.153
153.252.30.192.in-addr.arpa domain name pointer pages.github.com.
```

To redeploy it, you just have to push to the `gh-pages` branch in this repo.  In fact, assuming everything still works from when I set it up a few years ago, maven should do this automatically for you, just run:

```
mvn site:deploy
```

**Comment by ruifung** [comment]
It's still rather out of date, if anything, the javadocs there are still really out of date too.

**Comment by jroper** [comment]
Redeployed, and fixed and documented how to deploy the site for the next person in #126.

**Comment by benmccann** [comment]
Thank you James!
