### ISSUE TITLE
Serialization bug with nested fields

### ISSUE THREAD

**Issue by BenRomberg** [mongojack/mongojack#127]
When trying to build an `update` with a `DBQuery` having a nested field, the `SerializationUtils` use the type of the Entity instead of the nested type to serialize the field.

```
public class Entity {
  private String _id;
  private OtherType value;
}

public class OtherType {
  private YetAnotherType _id;
}
```

In this case, issuing a `update(DBQuery.is("value._id", <value>))` would try to serialize `<value>` as a `String` instead of a `YetAnotherType`. Don't know if it happens every time, but in my case it was certainly the issue.

The fix is really easy: https://github.com/mongojack/mongojack/blob/c526598277eb7735c602a76f2e2bdb8fd978edd4/src/main/java/org/mongojack/internal/util/SerializationUtils.java#L560 needs to reference `fieldSerializer` instead of `serializer`. I've implemented an adapter for `JacksonDBCollection` and `SerializationUtils` for my own implementation and it works like a charm.

Let me know if a PR would be accepted for this and I'll see if I can find the time to write tests for mongojack.

**Comment by lukepalmer** [comment]
There's been a flurry of activity lately (thanks Ben and James!) so I'd say go for the PR. I think a number of people have run into this.

**Comment by benmccann** [comment]
Thanks for the fix!
