### ISSUE TITLE
Cannot use views with custom ObjectMapper

### ISSUE THREAD

**Issue by mattwigway** [mongojack/mongojack#145]
The `JacksonDBCollection` constructor allows you to specify either a custom view _or_ a custom `ObjectMapper` but not both. At https://github.com/mongojack/mongojack/blob/master/src/main/java/org/mongojack/JacksonDBCollection.java#L2168 `this.objectMapper.writerWithView(this.view)` is called. `this.view` will always be null if you specify a custom objectmapper due to the available constructors, but you also can't bake a view into the serialization config of your custom `ObjectMapper` because that view will be overridden by `writerWithView`.

**Comment by o2-mesmer** [comment]
`JacksonDBCollection` doesn't seem exist in the project anymore at the time I'm writing this.

MongoJack seems to ignore View settings when they are passed as part of the `ObjectMapper`'s `serializationConfig`/`deserializationConfig`, but that is just as well as it is fiddly and there is an easy alternative: you can specify a view on the `JacksonMongoCollection` builder.

Ticket seems obsolete.

**Comment by rlodge** [comment]
Sure, I agree it seems obsolete given the changes since 2017.
