### ISSUE TITLE
Release for Mongo Driver 3.4?

### ISSUE THREAD

**Issue by BenRomberg** [mongojack/mongojack#148]
Since the last release is almost a year old and there's no current release available when using the mongodb-driver 3.4.2, could you please provide a new release with the bumped dependency as already available on the master branch?

Or is it safe to use version 2.6.1 together with mongodb-driver 3.4.2 in production?

**Comment by benmccann** [comment]
Done

**Comment by BenRomberg** [comment]
TYVM @benmccann !
