### ISSUE TITLE
Query.toString and Query.equals don't provide ways to verify objects.

### ISSUE THREAD

**Issue by cfogrady** [mongojack/mongojack#149]
I am working on a project that is starting to introduce mongoJack as a means of mapping our DB objects directly to POJOs.

I have noticed that the toString method seems to only show the hashcode and class name. This makes it difficult to see what a query actually ran in logs. It would be nice if the toString, or some other method provided the json that would be provided for the find statement.

I have also noticed that Query objects are not equal to each other even if they have the same exact contents. I would think that if the queries execute the same, they should be equal. I am trying to verify a queryBuilder I have in my code, but am unsure how to do so when neither the toString nor the equals methods behave as I would expect.

```
Query query = DBQuery.in("TEST_ID", Collections.EMPTY_LIST);
Query query2 = DBQuery.in("TEST_ID", Collections.EMPTY_LIST);
if(query.equals(query2)) System.out.println("Queries are equal!");
else System.out.println("Queries aren't equal!");
System.out.println(query.toString());
```

**Comment by AMTerp** [comment]
>  It would be nice if the toString, or some other method provided the json that would be provided for the find statement.

Agree with this especially, a useful toString on Query would be extremely helpful.
Seems to also have been requested in #22.

**Comment by rlodge** [comment]
You can get a string out of the returned Query object, if necessary, by transforming it to a BsonDocument and calling toString on that document.  First you would need to call initialize() on the query with your ObjectMapper, the JavaType the collection holds, and the JacksonCodecRegistry from your collection, and then call toBsonDocument.  It's a little convoluted, but it would get you a useful string in a pinch.  As I mentioned above, I don't plan to add functionality to the deprecated classes.
