### ISSUE TITLE
MongoJack website is down

### ISSUE THREAD

**Issue by maxkremer** [mongojack/mongojack#150]
mongojack.org has been down for a couple of days now.

**Comment by benmccann** [comment]
@jroper we might need your help on this one...

**Comment by jroper** [comment]
Sorry, that was my fault. I have a recollection that the domain name was transferred to somewhere else. The other day, I was doing some maintenance on my DNS manager, and I deleted a whole bunch of domain names that I no longer maintain, mongojack was deleted as part of that. I should have done a whois first to check whether I was still responsible for it. Anyway, I've reinstated the records, the nameservers should be resolving it within 15 minutes.

**Comment by jroper** [comment]
http://mongojack.org is back up.
