### ISSUE TITLE
underlying BSON unmarshalling creates a lot of garbage

### ISSUE THREAD

**Issue by sbodese** [mongojack/mongojack#151]
Hi, 

actually i figure out that the used underlying BSON unmarshalling creates a lot of garabage (round 540 MB) to unmashalling 4.7 MB of mongoDB objects. I m use the older mongojack version 2.6.1. Is here a better unmarshalling available in these newer versions of mongojack?

Cheers

Steffen

[
![bildschirmfoto 2017-07-05 um 11 53 34](https://user-images.githubusercontent.com/7249354/27859588-8f4bf138-6179-11e7-93d4-eebcfa21d79d.png)
](url)

**Comment by lyind** [comment]
`ObjectMapper.readValue(JsonParser, ...)` doesn't close the JsonParser instance. This looks like a feature that allows for fast de-serialization of multiple values in sequence.

`JacksonDBDecoder.decode()` needs to properly **close()** the DBDecoderBsonParser instance which implements **Closeable**.

What about something like:
```
        JacksonDBObject<T> decoded = new JacksonDBObject<T>();
        try(final DBDecoderBsonParser parser = new DBDecoderBsonParser(
                new IOContext(new BufferRecycler(), in, false), 0, in, decoded,
                dbCollection, objectMapper))
        {
            decoded.setObject((T) objectMapper.readValue(parser, type));
        }

        return decoded;
```

**Comment by benmccann** [comment]
Thanks. I've made that change here: https://github.com/mongojack/mongojack/commit/881f348c4cb575aeb501925ad53ea76005902fcc
