### ISSUE TITLE
JacksonMongoCollection doesn't work as expected

### ISSUE THREAD

**Issue by rlodge** [mongojack/mongojack#182]
Using the mongo driver version 3 classes (e.g. JacksonMongoCollection), objects with fields which use an EmbeddedObjectSerialzer will fail if the .save method (as opposed to .insert) are used.

In addition, the MongoCollection insert operations don't set the _id back in the object unless the Codec is a CollectibleCodec.

**Comment by benmccann** [comment]
Ok. Doing that now. It may take up to an hour to appear in Maven Central
