### ISSUE TITLE
Date field is getting IllegalArgumentException

### ISSUE THREAD

**Issue by loudywen** [mongojack/mongojack#187]
```Caused by: java.lang.IllegalArgumentException: JsonGenerator of type org.mongojack.internal.object.document.DocumentObjectGenerator not supported: org.mongojack.internal.DateSerializer is designed for use only with org.mongojack.internal.object.BsonObjectGenerator or org.mongojack.internal.stream.DBEncoderBsonGenerator or com.fasterxml.jackson.databind.util.TokenBuffer```

I am using the latest 2.9.4 mongojack. When I check the EmbeddedObjectSerializer. it only check BsonObjectGenerator or DBEncoderBsonGenerator. should we add the DocumentObjectGenerator as well?
```
 protected void writeEmbeddedObject(T value, JsonGenerator jgen)
            throws IOException {
        if (jgen instanceof BsonObjectGenerator || jgen instanceof DBEncoderBsonGenerator) {
            jgen.writeObject(value);
        } else if (jgen instanceof TokenBuffer) {
            TokenBuffer buffer = (TokenBuffer) jgen;
            ObjectCodec codec = buffer.getCodec();
            buffer.setCodec(null);
            buffer.writeObject(value);
            buffer.setCodec(codec);
        } else {
            String message = "JsonGenerator of type "
                    + jgen.getClass().getName()
                    + " not supported: " + getClass().getName()
                    + " is designed for use only with "
                    + BsonObjectGenerator.class.getName()
                    + " or "
                    + DBEncoderBsonGenerator.class.getName()
                    + " or "
                    + TokenBuffer.class.getName();
            throw new IllegalArgumentException(message);
        }
    }
```
It looks like if I use **insert** instead of **save**, then I am able to insert to mongodb. So I guess this is bug :(

**Comment by loudywen** [comment]
its same as this ticket [](https://github.com/mongojack/mongojack/issues/182)

**Comment by benmccann** [comment]
Closing as duplicate
