### ISSUE TITLE
Support Mongo Java Driver 3.11

### ISSUE THREAD

**Issue by rlodge** [mongojack/mongojack#191]
At my office we are planning updates to Mongo 4.2, and I would like get MongoJack to fully support the latest 3.11 driver, which supports the new java version.

My initial thought is that we can support it with no change _initially_ by updating the driver being used to `mongodb-driver-legacy:3.11.0`.  That would create minimal support.

Then I was thinking that really the project should be split into two modules, one supporting the legacy driver and one supporting only the new interfaces in `mongo-driver-sync:3.11.0`; I imagine eventually the legacy driver will be deprecated, and then we would be able to drop the unsupported module.

I wanted to put this issue out there to get people's opinions on how this should be done before I took a crack at it myself.

**Comment by benmccann** [comment]
Can you share some details about legacy vs non-legacy? I'm leaning towards suggesting just dropping the legacy stuff if no one else objects, but would like some more details

**Comment by rlodge** [comment]
Sure.  My understanding is that the "legacy" driver includes all of the deprecated things like `getDB` (vs the new `getDatabase`), the use of `DBCollection` instead of `MongoCollection`, etc.  The other drivers drop the deprecated stuff entirely.  Basically `JacksonDBCollection` uses the legacy stuff, and `JacksonMongoCollection` uses the new stuff.

I was thinking of separating them to ease the refactoring internally and to ease anyone's transition; if they've built around JacksonDBCollection they can use the legacy module; if they've built around JacksonDBCollection they can switch to the new driver and a new module; that's my thought, anyway.  I'm not sure how it will work out.

My suspicion is that an implementation built _purely_ on the non-deprecated code will be a much thinner wrapper of the underlying Mongo code.

**Comment by benmccann** [comment]
I'm happy with whatever you'd like to do. Supporting both or just the new stuff
