### ISSUE TITLE
MongoJackModule can't be configured with a custom ObjectMapper in OSGi

### ISSUE THREAD

**Issue by rakeshk15** [mongojack/mongojack#202]
Since MongoJackModule is in internal package therefore it is not accessible to register the custom ObjectMapper.

Basically this doesn't work in OSGi

**MongoJackModule.configure(myObjectMapper);**

One option would be to expose the internal package as well without any code change and this will be fully backward compatible. However, it breaks strong encapsulation which OSGi provides.

Fix/workaround - We just need to add one more package in maven-bundle-plugin

<Export-Package>org.mongojack,org.mongojack.internal</Export-Package>

if it is ok then I could provide a PR.

Thanks,
Rakesh

**Comment by rakeshk15** [comment]
or probably some other programmatic way where we just configure the MongoJackModule once with the custom ObjectMapper as we don't need to configure it per collection.

**Comment by rlodge** [comment]
Would adding a static helper in org.mongojack that did the configuration work?  I don't want to move the class and break backward compatibility.

**Comment by rakeshk15** [comment]
I completely agree on maintaining the backward compatibility.

Yes, a helper in exported package will work and **org.mongojack** is exported as per the manifest headers.
