### ISSUE TITLE
MongoJack breaks $lookup aggregation stage

### ISSUE THREAD

**Issue by o2-mesmer** [mongojack/mongojack#204]
In certain cases, MongoJack breaks lookup stages in aggregation pipelines, due (as far as I can tell) to its trying to JSON-encode the members of the pipeline.

Here's a simple bit of code that illustrates the issue:
```Java
        MongoDatabase db = ...
        MongoCollection<Document> mc = db.getCollection("test");
        mc.insertOne(new Document("key", "val"));

        List<Bson> pipeline = List.of(
            Aggregates.lookup(
                "test",
                List.of(
                    Aggregates.project(
                        Projections.fields(
                            Projections.excludeId(),
                            Projections.computed("insert", List.of("hello"))
                        )
                    )
                ),
                "inserts"
            ));

        mc.aggregate(pipeline).forEach((Consumer<Object>) o -> System.err.println("Without MongoJack: " + o));

        JacksonMongoCollection<Document> jmc = JacksonMongoCollection.builder().build(mc, Document.class);

        jmc.withDocumentClass(Map.class)
           .aggregate(pipeline).forEach((Consumer<Object>) o -> System.err.println("With MongoJack: " + o));

        JacksonCodecRegistry registry = new JacksonCodecRegistry(objectMapper){
            @Override
            public <T> Codec<T> get(Class<T> clazz, CodecRegistry registry) {
                if(BsonValue.class.isAssignableFrom(clazz)){
                    return null;
                } else {
                    return super.get(clazz, registry);
                }
            }
        };

        jmc.withDocumentClass(Map.class)
           .withCodecRegistry(registry)
           .aggregate(pipeline).forEach((Consumer<Object>) o -> System.err.println("With MongoJack and registry override: " + o));
```

The above prints, in turn:
```
Without MongoJack: Document{{_id=5ed6c350ae09870f2b4a463c, key=val, inserts=[Document{{insert=[hello]}}]}}
```
```
With MongoJack: {_id=5ed6c350ae09870f2b4a463c, key=val, inserts=[{insert=[{value=hello, bsonType=STRING, array=false, null=false, int64=false, dateTime=false, document=false, javaScript=false, decimal128=false, int32=false, objectId=false, symbol=false, string=true, timestamp=false, dbpointer=false, double=false, binary=false, boolean=false, number=false, javaScriptWithScope=false, regularExpression=false}]}]}
```
```
With MongoJack and registry override: {_id=5ed6c350ae09870f2b4a463c, key=val, inserts=[{insert=[hello]}]}
```

The issue (again, as far as I can tell) is caused by the `List.of("hello")` object in the pipeline being first wrapped by the Mongo driver to a `BsonArray` object with a `BsonString` member, and then being passed through Jackson's `com.fasterxml.jackson.databind.ser.std.CollectionSerializer`, which does standard introspection -- which it definitely shouldn't it this case. 

Providing a custom `JacksonCodecRegistry` which ignores `BsonValue` types seems to fix the issue, although I cannot judge what the side effects would be.

**Comment by rlodge** [comment]
I checked in a fix this morning and published a version 4.0.2-SNAPSHOT to oss.sonatype.org.  Can you confirm it works?

**Comment by o2-mesmer** [comment]
It does and I can. Nice job, man!

Any chance for this to be backported to the 3.x branch? I'm using mongo with spring-boot for easier integration, and they're on 3.x.

**Comment by rlodge** [comment]
I pushed this (also #202 and #201) to a branch for 3.x and deployed a 3.0.3-SNAPSHOT; let me know if it works.

**Comment by o2-mesmer** [comment]
Works swimmingly. I can reproduce and get rid of the error with the same code just by switching from 3.0.2 to 3.0.3-SNAPSHOT (and the actual code is quite bit more complex than the example I gave earlier).

Thank you very much!

**Comment by rlodge** [comment]
Release version 3.0.3 with this change.  Will wait a while before I put out 4.0.2
