### ISSUE TITLE
Upgrade dependencies if possible

### ISSUE THREAD

**Issue by rlodge** [mongojack/mongojack#207]
Upgrade dependencies, especially Jackson to 2.11

**Comment by MichaelSp** [comment]
at least jackson is covered in https://github.com/mongojack/mongojack/commit/6042f049e1ba3341452f90919cdbbf1608ec8027

**Comment by rlodge** [comment]
I can, but I'm reluctant to since the jackson version change is the only modification since the 4.0.2 release.  No code changes are necessary to use the library with Jackson 2.11, so there should be no issue with using the 4.0.2 release with Jackson 2.11.

**Comment by rlodge** [comment]
Latest jackson updated.
