### ISSUE TITLE
Is Async mongodb driver supported?

### ISSUE THREAD

**Issue by liorsl** [mongojack/mongojack#225]
Hi guys,
I know mongojack works with the mongo sync driver, however I am considering using the async driver in my project.
I know mongodb drivers use the same package names for both sync and async, I am not sure if I try that if I am gonna be facing any issues since currently I employ mongojack only via its custom codec registry (which I believe depends on mongodb's core and bson modules which are the same across the two driver types).
Is that supported / possible with Mongojack? Any input would be appreciated.

**Comment by liorsl** [comment]
> I've never tried it; I doubt it would work. Not opposed to somebody proposing how to make it work, but I don't have time to look at it myself.

Say I manage to split mongojack into core and sync modules, would you be open to accepting such a PR?

**Comment by rlodge** [comment]
Yes, assuming fully tested & etc, I'd be open to accepting such a PR.
