### ISSUE TITLE
Parameterized JavaTypes are no longer supported

### ISSUE THREAD

**Issue by marquiswang** [mongojack/mongojack#227]
Me again! In my port from 2.x to 3.x and higher, I've run into one last issue. On one hand, I'm fairly certain this is the last issue. On the other hand, I'm concerned this one isn't fixable. Figured I'd ask just in case.

The 2.x API used to support `JavaType` for the type.

```java
DBCollection collection = ...;
JavaType parameterizedType = objectMapper.getTypeFactory().constructParametricType(Foo.class, Bar.class, Baz.class);
JacksonDBCollection<Foo<Bar, Baz>, ObjectId> jacksonDBCollection = new JacksonDBCollection(collection, parameterizedType, ObjectId.class, objectMapper);
```

Whereas the new API only supports `Class`. This makes it impossible to serialize/deserialize parameterized types - instead, you are forced to make a non-parameterized subtype and serialize/deserialize that instead.

```java
JacksonMongoCollection<Foo> jacksonMongoCollection = JacksonMongoCollection.builder().build(database, collectionName, Foo.class, UuidRepresentation.JAVA_LEGACY);
```

Any thoughts about whether it is possible to support this?

**Comment by rlodge** [comment]
The _builder_ only supports class, but the JacksonMongoCollection actually uses a `JavaType` internally.  There's no reason why it can't accept it as part of the builder API, at least optionally.

**Comment by rlodge** [comment]
I modified the builder to accept either a `Class`, `JavaType`, or `TypeReference`.  It's not very type-safe, in that I can't make the `MongoCollection` itself easily accept a parameterized type, so there's some unchecked casts in the builder.  Deployed 4.7.1-SNAPSHOT and 4.5.2-SNAPSHOT.

**Comment by marquiswang** [comment]
Amazing! Thanks again @rlodge! I'll give this a try.

**Comment by marquiswang** [comment]
@rlodge I think I am sorry to report that this doesn't work if you have a non-trivial type in the type parameter - it just deserializes it into a Map representing the Bson object no matter what. I have not checked out master and tried to create a simple test case yet - I'll try to do that when I have time.

**Comment by rlodge** [comment]
Yeah, because the type doesn't make it very far into the decoding process.  A failing test is easy to make.  I'll have to think about how to fix it though

**Comment by rlodge** [comment]
I _think_ that your initial thinking was maybe correct, and that maybe it can't be fixed inside the `CodecRegistry` paradigm.  I could modify the `JacksonDecoder` and the `JacksonCodecRegistry` to be aware of a `JavaType`, but the fundamental interface of `CodecRegistry` deals with `Class` instances only, and so the Mongo driver internals won't do anything to guarantee that the `JavaType` is honored.

**Comment by rlodge** [comment]
I added a test in `TestJacksonMongoCollection` to serve as an example of how to use `JsonTypeInfo` which is the way I've done this sort of thing in the past.
