### ISSUE TITLE
The mongojack.org domain is up for renewal

### ISSUE THREAD

**Issue by jroper** [mongojack/mongojack#228]
Hi, I own and manage the mongojack.org domain. It's up for renewal, expiring on 12 February 2023. I'll renew it if no one else is prepared to take it over, but since I don't have anything to do with the project anymore, if anyone active on the project would rather own it, I'd love to transfer it. .org registrations cost US$12/year at Google domains.

**Comment by rlodge** [comment]
I'm willing to take it on, although to be honest I'm no longer working for a company that uses MongoDB every day, so I'm using this less frequently.

**Comment by jroper** [comment]
Up to you, if you're ready to receive it, the config needed is four A records from the apex to the following IPs:

185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153

And a CNAME record from www to mongojack.github.io.

Once you're ready to transfer, I'll initiate and send you the authorization code via email.

**Comment by rlodge** [comment]
Ok.  A-record and CNAME set up.

**Comment by jroper** [comment]
Ok, I've emailed you the code. Not sure if I used the right email address - I saw you've been committing to monojack with two email addresses, one seems to be your old employer, I didn't send it to that one.

**Comment by rlodge** [comment]
Thanks, I got it and initiated a transfer with the code.  Yes, I changed the email associated with the github account when I changed employers.

**Comment by jroper** [comment]
Great, I just got notified by my registrar that the transfer has been initiated. I think it gives me a week to cancel the transfer, and if I don't, then the transfer proceeds.

**Comment by jroper** [comment]
This appears to have been successfully transferred, thanks!
