### ISSUE TITLE
Set logger level

### ISSUE THREAD

**Issue by JimiIT92** [mongojack/mongojack#230]
Hi, is there a way to set the log verbosity of mongojack? Right now it looks like everything is being logged, even in production environments, which means that the log is filled with messages (like every time a connection is opened)

**Comment by rlodge** [comment]
As far as I know, all the logging goes through slf4j.  So if you've got an slf4j implementation on your classpath (e.g. slf4j-logback), you would configure logging levels through that mechanism.  I can't speak to what goes on in the mongo driver itself, but I think it uses slf4j too.
