### ISSUE TITLE
How to serialize dates as ISODate()

### ISSUE THREAD

**Issue by mbigatti** [mongojack/mongojack#239]
Hi. I have a simple POJO with fields of type `LocalDate` and `LocalDateTime`(`java.time`). I would have expected that they would be written in Mongo as `ISODate()` but they're serialized as strings. Is this the intended behaviour or I'm missing something?

Thank you

POJO:
```import java.time.LocalDate;
import java.time.LocalDateTime;

import org.bson.types.ObjectId;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data @AllArgsConstructor @NoArgsConstructor
public class EntityWithDate {
	@JsonProperty("_id")
	ObjectId id;

	@JsonProperty("date")
	LocalDate localDate;

	LocalDateTime localDateTime;
}
```

test code:

```
final MongoClientURI uri = new MongoClientURI("mongodb://localhost:27017");
final MongoClient mongoClient = new MongoClient(uri);
final MongoDatabase mongoDatabase = mongoClient.getDatabase("UNIT_TEST");

final JacksonMongoCollection<EntityWithDate> collection = JacksonMongoCollection.builder()
		.build(
			mongoDatabase,
			"test",
			EntityWithDate.class,
			UuidRepresentation.UNSPECIFIED);

EntityWithDate entity = new EntityWithDate(
		objectId(1),
		LocalDate.of(2000, 1, 1),
		LocalDateTime.of(2000, 1, 1, 0, 0));

collection.drop();
collection.insert(entity);
```

database:

```
db.getCollection("test").find({})

{
    "_id" : ObjectId("000000000000000000000001"),
    "localDateTime" : "2000-01-01T00:00:00",
    "date" : "2000-01-01"
}
```

**Comment by rlodge** [comment]
I believe it is the expected result.  There's a test in the codebase that makes sure this is the case.  My understand is that an ISODate() represents a point in the timeline, but a LocalDate does not.  If we translated from one to the other, in some ways, there would be a loss of fidelity:  the LocalDate recovered from the ISODate would potentially be different than the original.  Whereas using a string we can ensure it's the same LocalDate.

**Comment by mbigatti** [comment]
Thanks. Wouldn't `ZonedDateTime` also a point in the timeline?

**Comment by rlodge** [comment]
I think that both ZonedDateTime and OffsetDateTime also save as strings by default.  The behavior might depend on your Jackson ObjectMapper configuration.  Both of them contain _more_ information than Mongo wants to store in an ISODate:  time zone and offset aren't preserved by mongo in the ISODate object, so when you deserialized them they would no longer be equivalent.

I would _think_ that it would be fairly straightforward to add serializers / deserializers to the ObjectMapper to do what you're thinking.
