### ISSUE TITLE
Slow BsonDocumentCodec instantiation while decoding

### ISSUE THREAD

**Issue by hborchardt** [mongojack/mongojack#247]
Version 4.8.3
Hi, while profiling my application I saw that 50% of the time spent in `JacksonCodec.decode()` is actually spent constructing an instance of `BsonDocumentCodec`.

It is constructed here:
https://github.com/mongojack/mongojack/blob/c24369f43d9100fcf54f00114f51882d99ed10e0/src/main/java/org/mongojack/internal/stream/JsonParserAdapter.java#L37
Having one JsonParserAdapter instance per decode() call makes sense, because it holds parsing state. But I think the `withScopeCodec` property and its parameters have no state and just static arguments, so `withScopeCodec` could also be a static variable.

It would be cool to significantly speed up decoding by reusing this instance.

![image](https://github.com/user-attachments/assets/d0c5da37-a2ac-4659-a87f-4223cfdfdc08)

**Comment by rlodge** [comment]
You might be completely right, but I'm reluctant to risk statically holding all that state.  I published 5.0.2-SNAPSHOT and 4.8.4-SNAPSHOT to https://oss.sonatype.org/content/repositories/snapshots with a change to instantiate that json scope codec only when actually used, which I guess is in less than 1% of cases.  Test it out and let me know if that addresses your concerns.

**Comment by rlodge** [comment]
Since it's been deprecated that long, and the last operational version is 5.x, and that EOLs this month, and the 5.x images won't run on my apple silicon mac, I think we're justified in not testing the deprecated feature. 

Otherwise, you're good with the change?  I can cut a release if you are.

**Comment by hborchardt** [comment]
Yes, I am happy with the change and would appreciate it being released. For the `Code` deserialization I can also open another issue, it seems unrelated to this one as well as your changes.

**Comment by rlodge** [comment]
Released 5.0.2.  If the Code deserialization problem can be reproduced usefully in 6.x or 7.x, then file an issue.  Otherwise, I'm not concerned about it.
